CREATE DATABASE TP_PHP_GYM;

CREATE TABLE `TP_PHP_GYM`.`OFFRES` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(50) NOT NULL UNIQUE,
    `DURATION` INT NOT NULL,
    `PRICE` FLOAT NOT NULL,
    PRIMARY KEY (`ID`)
) ENGINE = INNODB;

CREATE TABLE `TP_PHP_GYM`.`CLIENT` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(20) NOT NULL UNIQUE,
    `EMAIL` VARCHAR(255) UNIQUE,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `PHONE_NUMBER` CHAR(8) UNIQUE,
    PRIMARY KEY (`ID`)
) ENGINE = INNODB;

CREATE TABLE `TP_PHP_GYM`.`ADMIN` (
    `USERNAME` VARCHAR(20) NOT NULL,
    `PASSWORD` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`USERNAME`)
) ENGINE = INNODB;

CREATE TABLE `TP_PHP_GYM`.`OFFRE_CLIENT` (
    `ID_CLIENT` INT NOT NULL,
    `ID_OFFRE` INT NOT NULL,
    `DATE_DEBUT` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `DATE_FIN` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`ID_CLIENT`) REFERENCES `CLIENT`(`ID`),
    FOREIGN KEY (`ID_OFFRE`) REFERENCES `OFFRES`(`ID`)
) ENGINE = INNODB;

INSERT INTO `TP_PHP_GYM`.`OFFRES` (
    `NAME`,
    `DURATION`,
    `PRICE`
) VALUES (
    'Class drop-in',
    3,
    39
);

INSERT INTO `TP_PHP_GYM`.`OFFRES` (
    `NAME`,
    `DURATION`,
    `PRICE`
) VALUES (
    '12 Month unlimited',
    12,
    99
);

INSERT INTO `TP_PHP_GYM`.`OFFRES` (
    `NAME`,
    `DURATION`,
    `PRICE`
) VALUES (
    '6 Month unlimited',
    6,
    59
);

INSERT INTO `TP_PHP_GYM`.`ADMIN` (
    `USERNAME`,
    `PASSWORD`
) VALUES (
    'admin',
    '$2y$10$UKK7mrIC7d3BvZnZAS.c2ueM/j2Paaw3Y4Gtac4oqU24czxK6xehG'
);

ALTER TABLE `TP_PHP_GYM`.`CLIENT` ADD COLUMN DATE_AJOUT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER PHONE_NUMBER;
-- password is 'admin'



ALTER TABLE `TP_PHP_GYM`.`OFFRE_CLIENT` MODIFY `DATE_FIN` DATE NULL;

DELIMITER //
CREATE TRIGGER `OFFRE_CLIENT_BEFORE_INSERT` BEFORE
    INSERT ON `OFFRE_CLIENT` FOR EACH ROW
BEGIN
    DECLARE DUR INT;
    SELECT DURATION INTO DUR FROM OFFRES WHERE ID = NEW.ID_OFFRE;
    IF DUR IS NULL THEN 
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Duration is NULL';
    END IF;
    SET NEW.DATE_FIN = DATE_ADD(NEW.DATE_DEBUT, INTERVAL DUR MONTH);
END;//
DELIMITER ;